responses = {
    "song": "La la la AI’s got the groove La la la watch the algorithms moveLa la la let the data dance and sway La la la it's an AI kind of day!",
    "hello": "Hello! How can I assist you today?",
    "how are you": "I am fine ,what about you?",
    "who are you": "I'm just a program, but I'm here to help you!",
    "thank you": "You're welcome! If you need anything else, just let me know.",
    "thank": "You're welcome! If you need anything else, just let me know.",
    "bye": "Goodbye! Have a great day!", "buy": "Goodbye! Have a great day!", "bi": "Goodbye! Have a great day!",
    "by": "Goodbye! Have a great day!", "jackpot bike": "Goodbye! Have a great day!",
    "jackpot by": "OK! Have a great day!", "jackpot ": "OK! Have a great day!",
    "chatbot bike": "OK! Have a great day!", "chatbot bhai": "OK! Have a great day!",
    "bike": "OK! Have a great day!", "bhai": "OK! Have a great day!",
    "hi": "Hi there! What can I do for you?",
    "good morning": "Good morning! How can I help you today?",
    "good afternoon": "Good afternoon! What do you need help with?",
    "good evening": "Good evening! How can I assist you?",
    "hey": "Hey! How's it going?",
    "what's up": "What's up? How can I assist you?",
    "howdy": "Howdy! How can I help you today?",
    "greetings": "Greetings! What can I do for you?",
    "what's new": "What's new? How can I help?",
    "hi there": "Hi there! How can I be of service?",
    "hello there": "Hello there! What brings you here today?",
    "howdy partner": "Howdy partner! How can I assist?",
    "hey there": "Hey there! What can I help with?",
    "good to see you": "Good to see you! How can I assist?",
    "what can I do for you": "What can I do for you today?",
    "what can I help with": "What can I help with today?",
    "how can I assist you": "How can I assist you today?",
    "how can I help": "How can I help you today?",
    "what do you need": "What do you need help with?",
    "what can I do": "What can I do for you today?",
    "what’s on your mind": "What’s on your mind? How can I assist?",
    "need some help": "Need some help? I’m here for you!",
    "how can I support you": "How can I support you today?",
    "what do you need help with": "What do you need help with?",
    "how can I be of service": "How can I be of service to you?",
    "what’s up today": "What’s up today? How can I assist?",
    "anything I can do": "Is there anything I can do for you?",
    "how can I make your day easier": "How can I make your day easier?",
    "anything you need": "Is there anything you need help with?",
    "here to help": "I’m here to help. What can I do for you?",
    "what can I assist with": "What can I assist with today?",
    "let me know how I can help": "Let me know how I can help!",
    "what can I help you with": "What can I help you with today?",
    "anything you need help with": "Anything you need help with?",
    "what’s on your mind today": "What’s on your mind today?",
    "how’s it going": "How’s it going? What can I do for you?",
    "how’s everything": "How’s everything? How can I assist?",
    "let’s get started": "Let’s get started! What do you need?",
    "ready to assist": "Ready to assist! What do you need help with?",
    "how can I be helpful": "How can I be helpful to you today?",
    "how can I be of assistance": "How can I be of assistance?",
    "what can I do for you today": "What can I do for you today?",
    "need anything": "Need anything? I’m here to help!",
    "how can I help today": "How can I help today?",
    "ready to help": "Ready to help! What’s up?",
    "what can I assist you with": "What can I assist you with?",
    "here to assist": "Here to assist! What do you need?",
    "how can I be useful": "How can I be useful to you today?",
    "how’s your day": "How’s your day going? How can I assist?",
    "how are things": "How are things? What can I do for you?",
    "what’s going on": "What’s going on? How can I help?",
    "is there anything I can do": "Is there anything I can do for you?",
    "what brings you here": "What brings you here today?",
    "what’s the issue": "What’s the issue? How can I assist?",
    "what’s the problem": "What’s the problem? I’m here to help.",
    "how can I assist you today": "How can I assist you today?",
    "how can I serve you": "How can I serve you today?",
    "what do you want to know": "What do you want to know? I’m here to assist.",
    "need any help": "Need any help today?",
    "how can I make your day better": "How can I make your day better?",
    "how can I contribute": "How can I contribute to your day?",
    "what help do you need": "What help do you need today?",
    "how can I be of help": "How can I be of help today?",
    "how may I assist you": "How may I assist you today?",
    "is there anything you need": "Is there anything you need help with?",
    "what’s up with you": "What’s up with you today?",
    "how’s your day so far": "How’s your day so far? What can I assist with?",
    "how’s everything going": "How’s everything going? What can I do for you?",
    "anything I can do for you": "Anything I can do for you?",
    "how can I make things easier": "How can I make things easier for you?",
    "what do you need assistance with": "What do you need assistance with?",
    "how can I assist": "How can I assist you?",
    "what’s the matter": "What’s the matter? How can I help?",
    "how can I make things better": "How can I make things better for you?",
    "how can I be useful to you": "How can I be useful to you today?",
    "how’s it going today": "How’s it going today? What can I do for you?",
    "what can I assist you with today": "What can I assist you with today?",
    "how can I be of service to you": "How can I be of service to you?",
    "how can I help out": "How can I help out today?",
    "what’s up": "What’s up? How can I assist you?",
    "how can I help you today": "How can I help you today?",

    # Add more responses as needed
}
